/*********************************************************************************************************************
Code:			Code for Operating a 4-joint Biped with Obstacle Detecting Capability 
Author:			Ankit Manerikar
Date Created:	3/20/2014
Last Update:	4/19/2014
Description:	The following code allows a 4-axis Biped to be operated autonomously with obstacle sensors 
                while responding to a binary input. 
				The setup consists of a a Biped Assembly that is controlled by a Partial Gait mechanism in which only 
				one limb is actuated while the other follows passive walking dynamics.
				The setup is operated using an ATmega16 microcontroller board which consists of the biped motion 
				functions, Rc servos that are driven by PWMs generated by the ATmega and are operated via a separate 
				motor driver circuit and digital IR sensors that detect obstacles withing of 50 mm with a binary output
				(Obstacle = Logic 1, No obstacle = 1).
				The Pin Connections for the Controller are as follows:
				PA.0	- 	Left  IR Sensor Input
				PA.1	- 	Right IR Sensor Input
				
				PB.0	-   Servo Motor 0 (Knee)
				PB.1	-   Servo Motor 1 (Hip)
				PB.2	-   Servo Motor 2 (Ankle)
				PB.3	-   Servo Motor 3 (Hip-Steer)
				
**********************************************************************************************************************/

#include <avr/io.h>
#include <avr/interrupt.h>
#include "servo4_avr.h"

unsigned int SteerAngle 	= 90;							// Variable to steer the leg left-right
unsigned int TurnAroundFlag = 0;


/* Function to generate biped walking motion through motors **********************************************************/
	void walk()		{   // step 1: 	    default standing position
						ServoMotorAngle(175,0);			//  knee
						ServoMotorAngle(140,1);			//	Hip
						ServoMotorAngle(150,2);			//  ankle
						ServoMotorAngle(SteerAngle,3);
						_delay_ms(200);
						
						//step 2: 		push leg forward, rest the dummy legs ahead 
						ServoMotorAngle(125,0);
						ServoMotorAngle(95,1);
						ServoMotorAngle(140,2);
						_delay_ms(200);

						//step 3:		raise leg upward, dummy legs act as support
						ServoMotorAngle(125,0);
						ServoMotorAngle(80,1);
						ServoMotorAngle(165,2);
						_delay_ms(200);

						//step 4:		move raised leg forward, dummy legs act as support
						ServoMotorAngle(175,0);
						ServoMotorAngle(80,1);
						ServoMotorAngle(165,2);
						_delay_ms(200);

						//step 5:		rest the leg down
						ServoMotorAngle(175,0);
						ServoMotorAngle(110,1);
						ServoMotorAngle(165,2);
						_delay_ms(200);					}

/* Function to generate default standing postion at initialization ***************************************************/
void BipedStand()	{	ServoMotorAngle(175,0);
						ServoMotorAngle(140,1);
						ServoMotorAngle(150,2);
						ServoMotorAngle(SteerAngle,3);
						_delay_ms(1000);				}

/* Function to BipedCheck operation of motors *****************************************************************************/
void BipedCheck()	{	ServoMotorAngle(140,0);			
						ServoMotorAngle(120,1);			
						ServoMotorAngle(135,2);			
						ServoMotorAngle(90,3);
						_delay_ms(1000);				}

/* Function to turn left ********************************************************************************************/
void BipedTurnLeft(){	BipedStand();
						_delay_ms(200);
	
						ServoMotorAngle(140,0);			//    knee
						ServoMotorAngle(120,1);			//    Hip
						ServoMotorAngle(135,2);			//    ankle
						_delay_ms(50);

						while(((PINA&0x03)==0x01)||((PINA&0x03)==0x03))					//   keep turning left
						{
						if(SteerAngle != 175)		{SteerAngle++;
													 ServoMotorAngle(SteerAngle,3);			// for hip motor
													 _delay_ms(50);}
						else						{break;}								//   stop if angle exceeds limit
						}
														}

/* Function to turn right ******************************************************************************************/
void BipedTurnRight(){	BipedStand();
						_delay_ms(200);
						
						ServoMotorAngle(140,0);			//    knee
						ServoMotorAngle(120,1);			//    Hip
						ServoMotorAngle(135,2);			//    ankle
						_delay_ms(50);

						while( ((PINA&0x03) == 0x02 ) || ((PINA&0x03) == 0x03 ) )  		// keep turning right 
						{
						if(SteerAngle != 5)			{SteerAngle--;
													 ServoMotorAngle(SteerAngle,3);			// for hip motor 
													 _delay_ms(50);}
						else						{break;	}								// stop if angle exceeds limit
						}	
														}

/* Function to turn back ******************************************************************************************/
void BipedTurnBack(){	TurnAroundFlag = 1;

						BipedStand();
						_delay_ms(200);
						
						ServoMotorAngle(140,0);			//    knee
						ServoMotorAngle(120,1);			//    Hip
						ServoMotorAngle(135,2);			//    ankle
						_delay_ms(50);

//Turn From Extreme Left to Extreme Right (Full 180 degrees) till a path with no obstacles is found

						while(TurnAroundFlag == 1)					
						 {
								SteerAngle++;
								ServoMotorAngle(SteerAngle,3);
								_delay_ms(50);
								
							if((PINA & 0x03) == 0x01) || (SteerAngle == 175))		{break;}
							
								SteerAngle--;
								ServoMotorAngle(SteerAngle,3);
								_delay_ms(50);
								
							if((PINA & 0x03)==0x02)||(SteerAngle == 5))			{break;}
							if((PINA & 0x03)==0x00))								{TurnAroundFlag = 0;}
						  }						  
				}
						
/******************************************************************************************************************/

int main()
 {
 
	servo_init();					// To initialize the PWM signal for servo motors
	BipedStand();					// Initial standing Position

	_delay_ms(100);					
	DDRB = 0x00;					
	DDRA = 0x00;					// PORTA initialized as sensor interface input
	
	while(1)
	{
		walk();						// default walking motion
			
		if((PINA&0x03)==0x00)   		{SteerAngle = 90;}			// if no obstacle move forward
			
		else if((PINA&0x03)==0x01)									// if obstacle is at left side
										{BipedTurnLeft();			
										 _delay_ms(100);
										 SteerAngle = 90;			// back to normal position after turning
										 BipedStand();			}	// default standing position
			
		else if((PINA&0x03)==0x02)									// if obstacle is at right side
										{BipedTurnRight();			
										 _delay_ms(100);		
										 SteerAngle = 90;			// back to default after turning
										 BipedStand();			}	// default standing position
		
		else if((PINA&0x03)==0x03)		{//BipedTurnBack();
										 _delay_ms(30);	
										 if((PINA&0x03)==0x03)
										 {	BipedTurnLeft();
											_delay_ms(100);
											BipedStand();
											
											BipedTurnRight();
											_delay_ms(100);
											BipedStand();}		}
		}
}
